/*
 * Load Shedding API
 *
 * Endpoints for Load Shedding Api
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LoadSheddingService.Swagger.Client.OpenAPIDateConverter;

namespace LoadSheddingService.Swagger.Model
{
    /// <summary>
    /// DayDO
    /// </summary>
    [DataContract(Name = "DayDO")]
    public partial class DayDO : IEquatable<DayDO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DayDO" /> class.
        /// </summary>
        /// <param name="slots">slots.</param>
        public DayDO(List<SlotDO> slots = default(List<SlotDO>))
        {
            this.Slots = slots;
        }

        /// <summary>
        /// Gets or Sets Slots
        /// </summary>
        [DataMember(Name = "slots", EmitDefaultValue = false)]
        public List<SlotDO> Slots { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DayDO {\n");
            sb.Append("  Slots: ").Append(Slots).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DayDO);
        }

        /// <summary>
        /// Returns true if DayDO instances are equal
        /// </summary>
        /// <param name="input">Instance of DayDO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DayDO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Slots == input.Slots ||
                    this.Slots != null &&
                    input.Slots != null &&
                    this.Slots.SequenceEqual(input.Slots)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Slots != null)
                {
                    hashCode = (hashCode * 59) + this.Slots.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
