/*
 * Load Shedding API
 *
 * Endpoints for Load Shedding Api
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = LoadSheddingService.Swagger.Client.OpenAPIDateConverter;

namespace LoadSheddingService.Swagger.Model
{
    /// <summary>
    /// StageDO
    /// </summary>
    [DataContract(Name = "StageDO")]
    public partial class StageDO : IEquatable<StageDO>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StageDO" /> class.
        /// </summary>
        /// <param name="stage">stage.</param>
        public StageDO(int stage = default(int))
        {
            this.Stage = stage;
        }

        /// <summary>
        /// Gets or Sets Stage
        /// </summary>
        [DataMember(Name = "stage", EmitDefaultValue = false)]
        public int Stage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StageDO {\n");
            sb.Append("  Stage: ").Append(Stage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StageDO);
        }

        /// <summary>
        /// Returns true if StageDO instances are equal
        /// </summary>
        /// <param name="input">Instance of StageDO to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StageDO input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Stage == input.Stage ||
                    this.Stage.Equals(input.Stage)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Stage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
